const sampleEvents = [
    {
        title: "Tech Conference 2025",
        description: "A conference that brings together tech enthusiasts to discuss the latest trends in AI and software development.",
        image: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        date: new Date("2025-06-15T09:00:00"),
        time: "09:00 AM",
        venue: "Tech Park, Silicon Valley",
        organizer: "Tech Innovators Ltd.",
        ticketPrice: 100,
        location: "Silicon Valley, California",
        country: "USA",
        reviews: [],
    },
    {
        title: "Music Festival 2025",
        description: "Join us for a weekend of live music from top artists, food trucks, and amazing vibes.",
        image: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        date: new Date("2025-08-01T18:00:00"),
        time: "06:00 PM",
        venue: "Sunset Arena, Los Angeles",
        organizer: "Music Fest Productions",
        ticketPrice: 75,
        location: "Los Angeles, California",
        country: "USA",
        reviews: [],
    },
    {
        title: "Art Exhibition 2025",
        description: "An exhibition showcasing the works of renowned local artists. Experience a mix of modern and contemporary art.",
        image: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        date: new Date("2025-09-05T10:00:00"),
        time: "10:00 AM",
        venue: "Art Gallery, New York City",
        organizer: "NYC Arts Foundation",
        ticketPrice: 0, // Free event
        location: "New York, New York",
        country: "USA",
        reviews: [],
    },
    {
        title: "Startup Pitch Event",
        description: "Aspiring entrepreneurs pitch their innovative ideas to a panel of investors for a chance to win funding.",
        image: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        date: new Date("2025-07-20T14:00:00"),
        time: "02:00 PM",
        venue: "Innovation Hub, San Francisco",
        organizer: "Startup Ventures",
        ticketPrice: 50,
        location: "San Francisco, California",
        country: "USA",
        reviews: [],
    },
    {
        title: "Tech Conference 2025",
        description: "A conference that brings together tech enthusiasts to discuss the latest trends in AI and software development.",
        image: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        date: new Date("2025-06-15T09:00:00"),
        time: "09:00 AM",
        venue: "Tech Park, Silicon Valley",
        organizer: "Tech Innovators Ltd.",
        ticketPrice: 100,
        location: "Silicon Valley, California",
        country: "USA",
        reviews: [],
    },
    {
        title: "Music Festival 2025",
        description: "Join us for a weekend of live music from top artists, food trucks, and amazing vibes.",
        image: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        date: new Date("2025-08-01T18:00:00"),
        time: "06:00 PM",
        venue: "Sunset Arena, Los Angeles",
        organizer: "Music Fest Productions",
        ticketPrice: 75,
        location: "Los Angeles, California",
        country: "USA",
        reviews: [],
    },
    {
        title: "Art Exhibition 2025",
        description: "An exhibition showcasing the works of renowned local artists. Experience a mix of modern and contemporary art.",
        image: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        date: new Date("2025-09-05T10:00:00"),
        time: "10:00 AM",
        venue: "Art Gallery, New York City",
        organizer: "NYC Arts Foundation",
        ticketPrice: 0, // Free event
        location: "New York, New York",
        country: "USA",
        reviews: [],
    },
    {
        title: "Startup Pitch Event",
        description: "Aspiring entrepreneurs pitch their innovative ideas to a panel of investors for a chance to win funding.",
        image: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        date: new Date("2025-07-20T14:00:00"),
        time: "02:00 PM",
        venue: "Innovation Hub, San Francisco",
        organizer: "Startup Ventures",
        ticketPrice: 50,
        location: "San Francisco, California",
        country: "USA",
        reviews: [],
    },
];

module.exports = {data: sampleEvents};
